runtime: python
env: flex

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
- url: games/tilebag/static
  static_dir: clientweb/static

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto
   
# Use a special gunicorn worker class to support websockets.
entrypoint: gunicorn -c gunicorn.conf.py server:app

runtime_config:
  python_version: 3

# Use only a single instance, so that this local-memory-only chat app will work
# consistently with multiple users. To work across multiple instances, an
# extra-instance messaging system or data store would be needed.
manual_scaling:
  instances: 1


# For applications which can take advantage of session affinity
# (where the load balancer will attempt to route multiple connections from
# the same user to the same App Engine instance), uncomment the folowing:

network:
  session_affinity: true

